### ISSUE TITLE
Catch and log exception when DB session factory creation fails due to an uncaught mapping exception

### ISSUE THREAD

**Issue by chhil** [jpos/jPOS-EE#167]
Have been running some tests to see what it would take to migrate from my old hibernate 3.6 to the current 5 something.

https://github.com/jpos/jPOS-EE/blob/7c9d143fb8058c2468ee5d4b8b6b7e805d00b8f6/modules/dbsupport/src/main/java/org/jpos/ee/DB.java#L180

When my hibernate cfg references a mapping that does have its getters setters set correctly an exception gets thrown at this line which is not caught and user has no idea what happened. One will see newSessionFactory being invoked everytime a db is used meaning that there is a problem somewhere and sessionFactory creation is failing. But root cause is not identified as org.hibernate.MappingException does not get caught and logged (at least in my test case).

I wrapped the above  referenced line in a try catch block with a printstacktrace only then do I know from the stack trace towards the end "Could not locate getter method for property [a.b.c.WebUserRoles#userId]"

Suggestion is to somehow make this visible to track misconfiguration or bad code.

```
org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:123)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:181)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:301)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:469)
	at org.hibernate.boot.internal.MetadataImpl.buildSessionFactory(MetadataImpl.java:195)
	at org.jpos.ee.DB.newSessionFactory(DB.java:191)
	at org.jpos.ee.DB.getSessionFactory(DB.java:160)
	at org.jpos.ee.DB.<init>(DB.java:123)
	at org.jpos.ee.DB.<init>(DB.java:95)
	at Test.main(Test.java:31)
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:91)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:116)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:413)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:604)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:125)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:88)
	... 19 more
Caused by: org.hibernate.PropertyNotFoundException: Could not locate getter method for property [a.b.c.WebUserRoles#userId]
	at org.hibernate.internal.util.ReflectHelper.findGetterMethod(ReflectHelper.java:465)
	at org.hibernate.property.access.internal.PropertyAccessBasicImpl.<init>(PropertyAccessBasicImpl.java:41)
	at org.hibernate.property.access.internal.PropertyAccessStrategyBasicImpl.buildPropertyAccess(PropertyAccessStrategyBasicImpl.java:27)
	at org.hibernate.mapping.Property.getGetter(Property.java:311)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildPropertyGetter(PojoEntityTuplizer.java:193)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:145)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:53)
	... 24 more

```

**Comment by ar** [comment]
`DB.open()` throws `HibernateException`. If you use code similar to the `Open` participant, that exception should get noticed in the Q2.log. See [Open, in line 42](https://github.com/jpos/jPOS-EE/blob/master/modules/txn/src/main/java/org/jpos/transaction/Open.java#L42).

**Comment by chhil** [comment]
Agreed.
